language: python
cache: pip
python:
  - '3.5'
install:
  - 'pip3 install homeassistant'
  - git clone https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer skyq/
  - mv skyq/custom_components config/custom_components
script:
  - 'mv secrets.yaml.sample secrets.yaml'
  - 'touch fullchain.pem'
  - 'touch privkey.pem'
  - 'hass -c . --script check_config | tee check.output'
  - '! less check.output | grep -q "Failed config"'
