language: python
cache: pip
python:
  - '3.5'

install:
  - git clone https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer.git skyq/
  - mv skyq/custom_components custom_components
  - 'pip3 install homeassistant'

script:
  - 'mv secrets.yaml.sample secrets.yaml'
  - 'touch fullchain.pem'
  - 'touch privkey.pem'
  - 'hass -c . --script check_config | tee check.output'
  - '! less check.output | grep -q "Failed config"'
