language: python
cache: pip
python:
  - '3.5'

before_install:

- sed -e '/hacs/,+2d' < configuration.yaml > configuration.yaml

install:
  - 'pip3 install homeassistant'

script:
  - 'mv secrets.yaml.sample secrets.yaml'
  - 'touch fullchain.pem'
  - 'touch privkey.pem'
  - 'hass -c . --script check_config | tee check.output'
  - '! less check.output | grep -q "Failed config"'
