language: python
cache: pip
python:
  - '3.5'

for file in $(find custom_components/ -name "manifest.json"); do cat "$file" | for req in $(jq .requirements[]); do python3 -m pip install $(echo "$req" | jq -r .) ; done ; done
  
install:
  - 'pip3 install homeassistant'

script:
  - 'mv secrets.yaml.sample secrets.yaml'
  - 'touch fullchain.pem'
  - 'touch privkey.pem'
  - 'hass -c . --script check_config | tee check.output'
  - '! less check.output | grep -q "Failed config"'
