#################################################################
#                                                               #
#           Home Assistant Main Configuration File              #
#                                                               #
#################################################################


default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  
  packages: !include_dir_merge_named configuration/package
  customize: !include_dir_merge_named configuration/customize
  
  
#################################################################
#                                                               #
#                           Enables                             #
#                                                               #
#################################################################


homekit:

system_health:

ios:

cloud:

discovery:

hacs:
  token: !secret hacs_token
  
tts:
  - platform: google_translate


#################################################################
#                                                               #
#                        Customizations                         #
#                                                               #
#################################################################


lovelace:
  mode: yaml

custom_updater:
  show_installable: false
  hide_sensor: false
  track:
    - components
    #- cards
    #- python_scripts
  component_urls:
    - https://raw.githubusercontent.com/keatontaylor/custom_components/master/custom_components.json
  #card_urls:
    #- https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    #- https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    #- https://raw.githubusercontent.com/maykar/custom-lovelace/master/tracker.json
    #- https://raw.githubusercontent.com/ljmerza/waze-card/master/updater.json
    #- https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json


#################################################################
#                                                               #
#                           Includes                            #
#                                                               #
#################################################################


konnected: !include configuration/include/konnected.yaml
alarm_control_panel: !include configuration/include/alarm.yaml
script: !include scripts.yaml
sensor: !include configuration/include/sensor.yaml






# Components
# group: !include_dir_merge_named configuration/group
