#################################################################
#                                                               #
#           Home Assistant Main Configuration File              #
#                                                               #
#################################################################


default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  
  
#################################################################
#                                                               #
#                           Enables                             #
#                                                               #
#################################################################


homekit:

system_health:

ios:

cloud:

discovery:

hacs:
  token: !secret hacs_token
  
tts:
  - platform: google_translate


#################################################################
#                                                               #
#                           Includes                            #
#                                                               #
#################################################################


packages: !include_dir_merge_named configuration/package
customize: !include_dir_merge_named configuration/customize
konnected: !include configuration/include/konnected.yaml
alarm_control_panel: !include configuration/include/alarm.yaml
script: !include scripts.yaml
sensor: !include configuration/include/sensor.yaml






# Components
# group: !include_dir_merge_named configuration/group
