#################################################################
#                                                               #
#           Home Assistant Main Configuration File              #
#                                                               #
#################################################################


default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  
  packages: !include_dir_merge_named configuration/package
  customize: !include_dir_merge_named configuration/customize
  
  
#################################################################
#                                                               #
#                           Enables                             #
#                                                               #
#################################################################


homekit:
  entity_config:
    alarm_control_panel.ha_alarm:
      code: !secret alarm_pin_code

system_health:

ios:

cloud:

discovery:

hacs:
  token: !secret hacs_token

    
#action:
#      service: tts.google_translate_say
#      entity_id: media_player.forked_daapd_output_james_s_airport_express
#      data:
#        message: 'May the Force be with you.'

#light:
#  - name: "Kitchen LED"
#    platform: mqtt
#    state_topic: ESPURNA-41E639/relay/0
#    command_topic: ESPURNA-41E639/relay/0/set
#    payload_on: 1
#    payload_off: 0
#    availability_topic: ESPURNA-41E639/status
#    payload_available: 1
#    payload_not_available: 0
#    brightness_state_topic: ESPURNA-41E639/brightness
#    brightness_command_topic: ESPURNA-41E639/brightness/set
#    rgb_state_topic: ESPURNA-41E639/rgb
#    rgb_command_topic: ESPURNA-41E639/rgb/set
#    color_temp_command_topic: ESPURNA-41E639/mired/set
#    white_value_state_topic: ESPURNA-41E639/channel/3
#    white_value_command_topic: ESPURNA-41E639/channel/3/set

#################################################################
#                                                               #
#                        Customizations                         #
#                                                               #
#################################################################


frontend:
  javascript_version: latest
  themes: !include_dir_merge_named configuration/themes

lovelace:
  mode: yaml

#################################################################
#                                                               #
#                           Includes                            #
#                                                               #
#################################################################


konnected: !include configuration/include/konnected.yaml
alarm_control_panel: !include configuration/include/alarm.yaml
script: !include scripts.yaml
sensor: !include configuration/include/sensor.yaml
automation: !include_dir_merge_name configuration/automations

logger:
  logs:
    RFXtrx: debug






# Components
# group: !include_dir_merge_named configuration/group
