title: Security

views:
  - title: Kiosk
    icon: mdi-shield-key
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: alarm-panel
            name: Test Alarm    
            entity: alarm_control_panel.ha_alarm
            show_keypad: true
            #title: Keypad
            style: '--alarm-color-disarmed: var(--label-badge-blue);'
            states:
              - arm_home
              - arm_away
              - arm_night
                     
#          - type: entities
#            entities:
#              - type: custom:fold-entity-row
#                head: light.kitchen_led
#                entities:
#                  - type: custom:slider-entity-row
#                    entity: light.kitchen_led
#

