title: Grange Road

resources:
  - url: /local/kiosk.js
    type: js
  - url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /local/community/fold-entity-row/fold-entity-row.js?track=true
    type: module
  - url: /local/community/alarm_control_panel-card/alarm_control_panel-card.js?v=5
    type: js
  - url: /local/community/lovelace-card-tools/lovelace-card-tools.js?v=1
    type: js
  - url: /local/community/lovelace-popup-card/lovelace-popup-card.js?track=true

views:
  - title: Kiosk
    icon: mdi:home-outline
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: alarm-panel
            entity: alarm_control_panel.ha_alarm
            show_keypad: true
            title: My Alarm
            style: '--alarm-color-disarmed: var(--label-badge-blue);'
            states:
              - arm_home
              - arm_away
          
          - type: entities
            entities:
              - light.kitchen_led
              - type: custom:slider-entity-row
                entity: light.kitchen_led
            
          - type: entities
            entities:
              - type: custom:fold-entity-row
                head: light.kitchen_led
                entities:
                  - type: custom:slider-entity-row
                  - entity: light.kitchen_led
      

          - type: custom:fold-entity-row
            head:
            type: section
            label: Nested
            entities:
              - type: custom:slider-entity-row
                head: light.kitchen_led
                entities:
                  - type: custom:fold-entity-row
                    head: light.kitchen_led
                    entities:
                      - light.kitchen_led
