title: Grange Road

resources:
  - url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /local/community/fold-entity-row/fold-entity-row.js
    type: module
  - url: /local/community/alarm_control_panel-card/alarm_control_panel-card.js?v=3
    type: js

views:
  - title: main
    icon: mdi:home-outline
    cards:

      - type: custom:alarm_control_panel-card
        entity: alarm_control_panel.alarm
        show_keypad: true
        title: My Alarm
        style: '--alarm-color-disarmed: var(--label-badge-blue);'
        states:
          - arm_home
          - arm_away
          
      - type: entities
        entities:
          - light.kitchen_led
          - type: custom:slider-entity-row
            entity: light.kitchen_led
            
      - type: entities
        entities:
          - type: custom:fold-entity-row
            head: light.kitchen_led
            entities:
              - type: custom:slider-entity-row
              - entity: light.kitchen_led
      

      - type: custom:fold-entity-row
        head:
          type: section
          label: Nested
        entities:
          - type: custom:slider-entity-row
            head: light.kitchen_led
            entities:
              - type: custom:fold-entity-row
                head: light.bed_light
                entities:
                  - light.bed_light
