title: Hassio Home

resources:
  - url: /local/community/lovelace-slider-entity-row/slider-entity-row.js?v=3.0
    type: module

views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: custom:alarm_control_panel-card
        entity: alarm_control_panel.alarm
        title: My Alarm
        states:
          - arm_home
          - arm_away    
          
      - type: entities
      entities:
        - light.espurna_41e639
        - type: custom:slider-entity-row
          entity: light.espurna_41e639
