title: Hassio Home

resources:
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js

views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: custom:alarm_control_panel-card
        entity: alarm_control_panel.alarm
        title: My Alarm
        states:
          - arm_home
          - arm_away    

      - type: entities
        entities:
          - light.espurna_41e639
          - type: custom:slider-entity-row
            entity: light.kitchen_light

