automation:
# Turns on lights 1 hour before sunset if people are home
# and if people get home between 16:00-23:00

  - alias: 'Remove new devices notification'
    trigger:
      - platform: state
        entity_id: persistent_notification.config_entry_discovery
        to: notifying
      - platform: homeassistant
        event: start
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: config_entry_discovery
 
